#!/bin/bash
# script to upload tif stacks in ~/Downloads/ to ARA

for var in "$@"
do
    python ingest_tif_stack.py -collection cell_detection -experiment cell_detection_"$var" -channel thresholded_img -tif_stack ../package-log/cell_detection_"$var"-thresholded.tiff --type image --new_channel True --config ./intern.cfg
done
