#!/bin/bash
# script to upload tif stacks in ~/Downloads/ to ARA

for var in "$@"
do
    python ingest_tif_stack.py -collection cell_detection -experiment cell_detection_"$var" -channel basic_predictions -tif_stack ../package-log/cell_detection_"$var"_predicted_empty.tiff --type annotation --new_channel True --source_channel raw_data --config ./intern.cfg
done
